### ISSUE TITLE
Error: 'unstable_batchedUpdates' is not exported

### ISSUE THREAD

**Issue by codealphago** [LianjiaTech/hetu#10]
Hi!I have the same problem when I yarn build:umd
Error: 'unstable_batchedUpdates' is not exported by node_modules\react-dom\inde
.js, imported by node_modules\mobx-react-lite\es\utils\reactBatchedUpdates.js

**Comment by good-father** [comment]
please try again. I have exclude  mobx/mobx-react/mobx-react-lite when build umd module. @codealphago

**Comment by codealphago** [comment]
Another new problem，when I yarn build:umd，the console output:
yarn run v1.22.10
$ tsdx build --format umd --name Hetu
⠧ Building modules  54%                 14.5s, estimated 26.8s
Use of eval is strongly discouraged, as it poses security risks and may cause is
⠇ Building modules  56%                 15.2s, estimated 26.8s
Use of eval is strongly discouraged, as it poses security risks and may cause is
sues with minification
⠙ Building modules  73%                 19.5s, estimated 26.8s
[tsdx]: Your rootDir is currently set to "./". Please change your rootDir to "./
src".
TSDX has deprecated setting tsconfig.compilerOptions.rootDir to "./" as it cause
d buggy output for declarationMaps and more.
You may also need to change your include to remove "test", which also caused dec
✓ Building modules 20.1 secs
Done in 26.29s.

**Comment by codealphago** [comment]
ok,it works
