### ISSUE TITLE
TypeError: Cannot destructure property `host` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by OnePieceBTM** [LianjiaTech/hetu#13]
第三步，serve 目录 执行yarn dev 的时候报这个错误，（TypeError: Cannot destructure property `host` of 'undefined' or 'null'.）查阅资料说webpack-server 版本太高了，安装换成webpack-dev-server@3.0 也不行，请问如何解决？

**Comment by sealzrt** [comment]
根目录下  system_config.ini  去掉注释内容, 试一试

**Comment by good-father** [comment]
楼上正解👍
