### ISSUE TITLE
[Bug Report] 登录后台，提示密码错误

### ISSUE THREAD

**Issue by ly525** [LianjiaTech/hetu#14]
1. 我的账号 lambert.me@foxmail.com 以及 lantern.done@gmail.com 
2. 多次尝试 、reset 密码，均提示密码错误
3. 麻烦协助调查下

**Comment by good-father** [comment]
@ly525 您好, 可以尝试一下这个公共账号 
m18825144569@163.com 
123456

**Comment by georgezouq** [comment]
@ly525 @good-father  应该是用sql文件生成的数据库表吧 email字段太短了 我也遇到这个问题了 [提了PR](https://github.com/LianjiaTech/hetu/compare/master...georgezouq:patch-1)
