### ISSUE TITLE
mobx-react-lite和react-dom的版本问题

### ISSUE THREAD

**Issue by Gabriel0402** [LianjiaTech/hetu#5]
编译plugin的时候报错：
`Error: 'unstable_batchedUpdates' is not exported by node_modules/react-dom/index.js, imported by node_modules/mobx-react-lite/es/utils/reactBatchedUpdates.js`

这是mobx-react-lite和react-dom的版本问题吗

**Comment by good-father** [comment]
> 编译plugin的时候报错：
> `Error: 'unstable_batchedUpdates' is not exported by node_modules/react-dom/index.js, imported by node_modules/mobx-react-lite/es/utils/reactBatchedUpdates.js`
> 
> 这是mobx-react-lite和react-dom的版本问题吗

已修复

**Comment by Gabriel0402** [comment]
pull了最新版还是有问题，
"Error: 'unstable_batchedUpdates' is not exported by node_modules/react-dom/index.js, imported by node_modules/mobx-react/node_modules/mobx-react-lite/es/utils/reactBatchedUpdates.js"

mobx-react也有mobx-react-lite？
