### ISSUE TITLE
server启动问题

### ISSUE THREAD

**Issue by Gabriel0402** [LianjiaTech/hetu#6]
在启动server之后报错：
`Cannot destructure property 'host' of 'lodash_1.default.get(...)' as it is undefined.`

不是很明白是什么原因

**Comment by good-father** [comment]
在项目根目录下, 创建 system_config.ini 配置文件, 参考 [readme.md](https://github.com/LianjiaTech/hetu#4-%E5%88%9B%E5%BB%BA%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

**Comment by Gabriel0402** [comment]
是按照readme来做的，是在根目录下配置system_config.ini。

最新的readme里面去掉了client cdn也会导致client 报错。在ini里面加入client和cdn就可以了。
然后server还是报同样的错，Cannot destructure property 'host' of 'lodash_1.default.get(...)' as it is undefined.

**Comment by good-father** [comment]
> 是按照readme来做的，是在根目录下配置system_config.ini。
> 
> 最新的readme里面去掉了client cdn也会导致client 报错。在ini里面加入client和cdn就可以了。
> 然后server还是报同样的错，Cannot destructure property 'host' of 'lodash_1.default.get(...)' as it is undefined.

进入 `server/src/config/_prod.ts` 文件, 打印一下config,  看看 email, mysql 里面的host属性是否存在 @Gabriel0402

**Comment by Gabriel0402** [comment]
得到很奇怪的结果：
```
{
  server: { port: '9536' },
  client: {
    cdn_host: '',
    '[mysql]': true,
    host: '',
    port: '3306',
    user: 'root',
    password: '',
    database: ''
  }
}
```
mysql被默认为一个属性，而不是像server和client那样。然后我把mysql换到第一个也是一样的结果，感觉mysql是个关键词，只能被当成属性？我用的mac系统。

**Comment by good-father** [comment]
我也是mac系统, 看样子是你的配置文件 system_config.ini 格式有问题。

**Comment by Gabriel0402** [comment]
是格式的问题。。
