### ISSUE TITLE
mobx-react 和 react-dom兼容性问题

### ISSUE THREAD

**Issue by Gabriel0402** [LianjiaTech/hetu#9]
pull了最新版还是有问题，
"Error: 'unstable_batchedUpdates' is not exported by node_modules/react-dom/index.js, imported by node_modules/mobx-react/node_modules/mobx-react-lite/es/utils/reactBatchedUpdates.js"

mobx-react也有mobx-react-lite？

**Comment by good-father** [comment]
我又改了一版，打包umd模块时，排除了mobx/mobx-react/mobx-react-lite. 请再试一试。 @Gabriel0402
